config/routes.rb
CarrierwaveQiniuExample::Application.routes.draw do
  root :to => 'screenshots#index'
  resources :screenshots

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  attr_accessible :image, :name

  mount_uploader :image, ScreenshotUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  # GET /screenshots
  # GET /screenshots.json
  def index
    @screenshots = Screenshot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @screenshots }
    end
  end

  # GET /screenshots/1
  # GET /screenshots/1.json
  def show
    @screenshot = Screenshot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @screenshot }
    end
  end

  # GET /screenshots/new
  # GET /screenshots/new.json
  def new
    @screenshot = Screenshot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @screenshot }
    end
  end

  # GET /screenshots/1/edit
  def edit
    @screenshot = Screenshot.find(params[:id])
  end

  # POST /screenshots
  # POST /screenshots.json
  def create
    @screenshot = Screenshot.new(params[:screenshot])

    respond_to do |format|
      if @screenshot.save
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully created.' }
        format.json { render json: @screenshot, status: :created, location: @screenshot }
      else
        format.html { render action: "new" }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /screenshots/1
  # PUT /screenshots/1.json
  def update
    @screenshot = Screenshot.find(params[:id])

    respond_to do |format|
      if @screenshot.update_attributes(params[:screenshot])
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenshots/1
  # DELETE /screenshots/1.json
  def destroy
    @screenshot = Screenshot.find(params[:id])
    @screenshot.destroy

    respond_to do |format|
      format.html { redirect_to screenshots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carrierwave Qiniu Example</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/screenshots/_form.html.erb
<%= form_for(@screenshot) do |f| %>
  <% if @screenshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

      <ul>
      <% @screenshot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/screenshots/edit.html.erb
<h1>Editing screenshot</h1>

<%= render 'form' %>

<%= link_to 'Show', @screenshot %> |
<%= link_to 'Back', screenshots_path %>

app/views/screenshots/index.html.erb
<h1>Listing screenshots</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @screenshots.each do |screenshot| %>
  <tr>
    <td><%= screenshot.name %></td>
    <td><%= image_tag( screenshot.image.url  + '?' + screenshot.updated_at.to_s ) %></td>
    <td><%= link_to 'Show', screenshot %></td>
    <td><%= link_to 'Edit', edit_screenshot_path(screenshot) %></td>
    <td><%= link_to 'Destroy', screenshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Screenshot', new_screenshot_path %>

app/views/screenshots/new.html.erb
<h1>New screenshot</h1>

<%= render 'form' %>

<%= link_to 'Back', screenshots_path %>

app/views/screenshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @screenshot.name %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag( @screenshot.image.url + '?' + @screenshot.updated_at.to_s ) %>
</p>


<%= link_to 'Edit', edit_screenshot_path(@screenshot) %> |
<%= link_to 'Back', screenshots_path %>